import Foundation

public enum MarkdownExporter {
    /// Formats a Capture snapshot as a markdown block for the daily file.
    public static func format(_ capture: CaptureSnapshot) -> String {
        var lines: [String] = []

        // Timestamp header
        let time = DateFormatters.time.string(from: capture.createdAt)
        lines.append("## \(time)")
        lines.append("")

        // Content
        if capture.type == .url, let url = capture.sourceURL {
            let title = capture.sourceTitle ?? capture.content
            lines.append("[\(title)](\(url))")
        } else {
            lines.append(capture.content)
        }
        lines.append("")

        // Metadata
        var meta: [String] = []
        if let domain = capture.sourceDomain {
            meta.append("Source: \(domain)")
        }
        if let bundleID = capture.sourceBundleID {
            meta.append("App: \(bundleID)")
        }
        meta.append("Method: \(capture.method.rawValue)")

        if !capture.tags.isEmpty {
            meta.append("Tags: \(capture.tags.joined(separator: ", "))")
        }

        if let summary = capture.aiSummary {
            meta.append("AI: \(summary)")
        }

        lines.append(meta.joined(separator: " · "))
        lines.append("")
        lines.append("---")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    /// Formats a DigestSnapshot as a standalone markdown file.
    public static func formatDigest(_ digest: DigestSnapshot) -> String {
        var lines: [String] = []
        let dateStr = DateFormatters.isoDate.string(from: digest.date)

        lines.append("# Daily Digest — \(dateStr)")
        lines.append("")
        lines.append("> \(digest.captureCount) captures")
        lines.append("")
        lines.append(digest.summary)
        lines.append("")

        if let model = digest.modelUsed {
            lines.append("---")
            lines.append("*Generated by \(model)*")
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    /// Formats a ProfileSnapshot as a standalone markdown file.
    public static func formatProfile(_ profile: ProfileSnapshot) -> String {
        var lines: [String] = []
        let dateStr = DateFormatters.isoDate.string(from: profile.updatedAt)

        lines.append("# AI Profile")
        lines.append("")
        lines.append("> Last updated: \(dateStr) · Based on \(profile.lastCaptureCountAtGeneration) captures")
        lines.append("")
        lines.append(profile.fullText)
        lines.append("")

        return lines.joined(separator: "\n")
    }
}
